### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by liquidxtc13** [MaterialPrime/material-prime#10]
Material icons appear to not be working. Also: Icon page in documentation on your homepage is messed up. You should have another look at it.
I also couldn't find any reference to icons in the current code on github.

**Comment by francesco-strazzullo** [comment]
Hi @liquidxtc13, you can find all the icons on this page [Icons](http://www.materialprime.com/components/icon.xhtml). I will add also a little example with the Page and the Bean like other components.
