### ISSUE TITLE
Converter in SelectOne not working

### ISSUE THREAD

**Issue by serralha85** [MaterialPrime/material-prime#12]
When using SelectOne with a custom converter it doesn't render properly.

Tested the same converter with primefaces SelectOneMenu and worked fine.

**Comment by serralha85** [comment]
After 2 days finally found.... a typo.
It's working fine

**Comment by francesco-strazzullo** [comment]
Hi @serralha85 the typo is in your project or in our library?

**Comment by serralha85** [comment]
Sorry not to make it clear. It was in my project.
