### ISSUE TITLE
 incompatibility with PF Premium Themes

### ISSUE THREAD

**Issue by ybendek** [MaterialPrime/material-prime#2]
Hello again :)

I'm trying to use the fixed action button component (awesome component). However I have lot of css conflicts using this library with Primefaces Premium Themes, mainly the Rio theme, based in google material design.

Here is the demo page: http://www.primefaces.org/rio/

The main problem is related with the component itself, as you can see in the next screenshot, the icons are not centered
![image](https://cloud.githubusercontent.com/assets/13785120/12330533/9feaf69c-bab3-11e5-933f-c65780a9bfdb.png)

In the other hand I have problems with components used with the rio theme, for example an empty page looks like this picture:
![image](https://cloud.githubusercontent.com/assets/13785120/12330492/6f4c9018-bab3-11e5-9774-6fb29cfd5509.png)

However when this component is introduced some components change like the buttons at the upper corner:
![image](https://cloud.githubusercontent.com/assets/13785120/12330453/3e303548-bab3-11e5-9317-efa6eee9fe9a.png)

**Comment by francesco-strazzullo** [comment]
Hi ybendek,
MaterialPrime has his own css files. The project itself it's based on [Materialize](http://materializecss.com/). So it's very difficult to use it with custom primefaces themes. I've not access to the Rio Layout project so we cannot fix this.
